version: "3"

services:

  database:
    image: "postgres:11"
    environment:
      POSTGRES_USER: omero
      POSTGRES_DB: omero
      POSTGRES_PASSWORD: omero
    networks:
      - omero
    ports:
      - "5432:5432"
    volumes:
      - "database:/var/lib/postgresql/data"

  omeroserver:
    image: "openmicroscopy/omero-server:5.6"
    environment:
      CONFIG_omero_db_host: database
      CONFIG_omero_db_user: omero
      CONFIG_omero_db_pass: omero
      CONFIG_omero_db_name: omero
      ROOTPASS: omero
    networks:
      - omero
    ports:
      - "4063:4063"
      - "4064:4064"
    volumes:
      - "omero:/OMERO"

  # 原始版本
  # omeroweb:
  #   image: "openmicroscopy/omero-web-standalone:5.6"
  #   environment:
  #     OMEROHOST: omeroserver
  #   networks:
  #     - omero
  #   ports:
  #     - "4080:4080"

  omeroweb:
    image: "openmicroscopy/omero-web-standalone:5.6"
    environment:
      PYTHONPATH: /opt/omero/web/venv3/bin:/omero-iviewer/plugin
      OMEROHOST: omeroserver
    networks:
      - omero
    ports:
      - "4080:4080"
    volumes:
      - "/opt/work/omero/omero-iviewer:/omero-iviewer"


networks:
  omero:

volumes:
  database:
  omero:
